auto: true
safe: true
server: true
markdown: kramdown
pygments: true
permalink: /:title.html

default_theme: bright
default_body_class: list

author:
    name: Roman Komarov
    url:  http://kizu.ru/

fork_url: https://github.com/kizu-test-account/jekyll-shower
progress: true
